const apiUrl = "https://api.thenewsapi.com/v1/news/top";
const apiToken = "gMPB3SiL40yu49HDd3jxZ6YdutPsiJYsXv7DCr1V";
//create container content generated by js
const contentContainer = document.createElement("div");
contentContainer.classList.add("content-container");
document.body.appendChild(contentContainer);

// create container to be able to clear content
const mainContainer = document.querySelector(".main");
console.log(mainContainer);

//fetch current date
const currentDate = new Date();
const formattedDate = currentDate.toISOString().split("T")[0].slice(0, 7);

//adding eventlisteners for each button
document.addEventListener("DOMContentLoaded", function () {
  document.getElementById("general").addEventListener("click", function () {
    changeCategory("general");
  });
  document.getElementById("politics").addEventListener("click", function () {
    changeCategory("politics");
  });
  document.getElementById("business").addEventListener("click", function () {
    changeCategory("business");
  });
  document.getElementById("tech").addEventListener("click", function () {
    changeCategory("tech");
  });
  document.getElementById("science").addEventListener("click", function () {
    changeCategory("science");
  });
  document.getElementById("sports").addEventListener("click", function () {
    changeCategory("sports");
  });

  //button onclick function that changes the APIurl to specified category
  function changeCategory(newCategory) {
    //check if content exists, if true, clear.
    if (contentContainer && mainContainer) {
      contentContainer.innerHTML = "";
      mainContainer.innerHTML = "";
    } else {
      console.error("Container not found");
    }

    //set new parameters
    const params = new URLSearchParams({
      language: "en",
      categories: newCategory,
      published_after: formattedDate,
    });

    // encode params to url
    const urlParams = new URLSearchParams(params);
    const apiUrlEncoded = `${apiUrl}?${urlParams.toString()}`;

    //fetch for api
    fetch(apiUrlEncoded, {
      method: "GET",
      headers: {
        "Content-type": "application/json",
        Authorization: `Bearer ${apiToken}`,
      },
    })
      .then((response) => {
        if (!response.ok) {
          throw new Error("Error HTTP!");
        }
        return response.json();
      })
      .then((news) => {
        news.data.forEach((article) => {
          //create individual container for each article to be able to clear it when changing category
          const articleContainer = document.createElement("div");
          articleContainer.classList.add("article-container");

          //crete img
          const heroImage = document.createElement("img");
          heroImage.src = article.image_url;
          heroImage.classList.add("hero_image");
          articleContainer.appendChild(heroImage);

          //create title
          const title = document.createElement("div");
          title.innerHTML = `
<h1>${article.title}</h1>
`;
          title.classList.add("title");
          articleContainer.appendChild(title);

          //create snippet
          const snippet = document.createElement("div");
          snippet.innerHTML = `
<p>${article.snippet}</p>
`;
          snippet.classList.add("snippet");
          articleContainer.appendChild(snippet);

          //create source
          const source = document.createElement("div");
          source.innerHTML = `
      <p>Source: ${article.source}</p>
      `;
          source.classList.add("source");
          articleContainer.appendChild(source);

          // apend container to ba able to clear
          contentContainer.appendChild(articleContainer);
        });
      })
      .catch((error) => {
        console.error("Error fetching data:", error);
      });
  }
});
